// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhX6snxQkdb5LoWTU-toAu4etuL8hCLQ',
    appId: '1:652079747147:web:e610a8aab1cb611bf9bdce',
    messagingSenderId: '652079747147',
    projectId: 'fyp-mobile-app-cbe7a',
    authDomain: 'fyp-mobile-app-cbe7a.firebaseapp.com',
    storageBucket: 'fyp-mobile-app-cbe7a.firebasestorage.app',
    measurementId: 'G-XCG2C2XTFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0Qjsi3Vt5Nw066E0teyJekwDDCb9-Ms',
    appId: '1:652079747147:android:e74b35d6634ab8f6f9bdce',
    messagingSenderId: '652079747147',
    projectId: 'fyp-mobile-app-cbe7a',
    storageBucket: 'fyp-mobile-app-cbe7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJA5u3aEC3FT30Aq8AANJEVDyTxm5xd-E',
    appId: '1:652079747147:ios:035fd5c258b58603f9bdce',
    messagingSenderId: '652079747147',
    projectId: 'fyp-mobile-app-cbe7a',
    storageBucket: 'fyp-mobile-app-cbe7a.firebasestorage.app',
    iosBundleId: 'com.example.fypP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJA5u3aEC3FT30Aq8AANJEVDyTxm5xd-E',
    appId: '1:652079747147:ios:035fd5c258b58603f9bdce',
    messagingSenderId: '652079747147',
    projectId: 'fyp-mobile-app-cbe7a',
    storageBucket: 'fyp-mobile-app-cbe7a.firebasestorage.app',
    iosBundleId: 'com.example.fypP2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFhX6snxQkdb5LoWTU-toAu4etuL8hCLQ',
    appId: '1:652079747147:web:8ec0e3d5c8dcdafff9bdce',
    messagingSenderId: '652079747147',
    projectId: 'fyp-mobile-app-cbe7a',
    authDomain: 'fyp-mobile-app-cbe7a.firebaseapp.com',
    storageBucket: 'fyp-mobile-app-cbe7a.firebasestorage.app',
    measurementId: 'G-JH6QD3J4E2',
  );
}
